### ISSUE TITLE
Added PrimeHub

### ISSUE THREAD

**Issue by gblpedia** [mlops-platforms/mlops-platforms#1]
Added PrimeHub in the last column of the [spreadsheet](https://docs.google.com/spreadsheets/d/108lUOxyRc9PWfbSHTw61tHQ5iThwEvrX53n94JVlJD4/edit?usp=sharing).
Please review it and inform us if ay problem.

Many thanks

**Comment by ryandawsonuk** [comment]
I've added a column to the public master sheet. I've mostly taken your text and edited it a bit to keep the language neutral and make it a little shorter. Let me know if there's anything that you would like us to change.

**Comment by gblpedia** [comment]
Thank you for the help. It looks great.
