### ISSUE TITLE
Added Prevision.io

### ISSUE THREAD

**Issue by florian-laroumagne** [mlops-platforms/mlops-platforms#2]
Hi guys,

I have added the column Prevision.io to the document : https://docs.google.com/spreadsheets/d/1votwVNGxWEHqDez7BamgxxjHpGsG23xOMUOqC7mZyOQ/edit?usp=sharing

Feel free to update the main spreadsheet accordingly.
Regards,
Florian @ Prevision.io

**Comment by ryandawsonuk** [comment]
I've modified the language a little bit to keep it neutral and added it to the master sheet. Let us know if there's anything you'd like us to change.

**Comment by florian-laroumagne** [comment]
Thanks for the fast update!

Do you know how to be listed here :
https://github.com/thoughtworks/mlops-platforms/#platform-profiles
Is it an article written by you that fits your understanding of vendors'
products ? Or is it written by vendors directly and shipped to you?

Regards,

*Florian Laroumagne*

*Co-Founder & Chief Data Scientist*
+33 6 31 35 69 84
162 rue de Rivoli - 75001 Paris

*_____________________________________________*


[image: prevision.io] <http://prevision.io/>[image:
https://www.linkedin.com/company/10981318]
<https://www.linkedin.com/company/10981318> [image:
https://twitter.com/PrevisionIO] <https://twitter.com/PrevisionIO> [image:
https://www.instagram.com/prevision.io/]
<https://www.instagram.com/prevision.io/>




Le jeu. 2 déc. 2021 à 17:16, Ryan Dawson ***@***.***> a
écrit :
