### ISSUE TITLE
Iguazio - Please add our column

### ISSUE THREAD

**Issue by jasonnIguazio** [mlops-platforms/mlops-platforms#3]
Hello,
I would like to add our column to the spreadsheet.
This is the link to my copy. If you need to have it uploaded please let me know,
https://docs.google.com/spreadsheets/d/1PqUVgup6C1tRckdg2vDt6NYHiZlJQgiSaDhEEKD4fVA/edit?usp=sharing

Thanks,
Jason Novich
Technical Writer - Iguazio.com

**Comment by ryandawsonuk** [comment]
Could you add some links to the product documentation for some of those features? I see links in the 'product focus' and 'pricing' rows but not in the rows highlighting features

**Comment by jasonnIguazio** [comment]
I have added links to the categories in the features sections.
Let me know if there is anything else that I should add.
Thanks,
Jason Novich
Technical Writer - Iguazio.com

**Comment by ryandawsonuk** [comment]
I've made some minor alterations and added the column to the public version now. Let us know if there's anything you'd like to be changed.
