### ISSUE TITLE
Adding Neptune.ai to MLOps Platforms

### ISSUE THREAD

**Issue by domikoz** [mlops-platforms/mlops-platforms#6]
Hi,
I'd love to add Neptune.ai to the spreadsheet. [Here](https://docs.google.com/spreadsheets/d/1dj-SprRfc88nCFxBmNwS2XyOqnwpB6r-JRpdeAltb5s/edit?usp=sharing) you can find the updated file. 

I added column Q with all the necessary details about Neptune.ai, no other changes have been made. 

Thanks!

**Comment by ryandawsonuk** [comment]
I've now integrated this with a few changes. The main changes were in rows 9 and 10. I've referenced https://neptune.ai/blog/how-to-monitor-your-models-in-production-guide to explain that neptune is a metadata store with a focus on experimentation and training, not a production observability tool. Rows 9 and 10 are primarily about production observability.

**Comment by ryandawsonuk** [comment]
Let me know if there's anything about the entry that you'd like changed

**Comment by domikoz** [comment]
Thanks for the super fast update, looks great!
