### ISSUE TITLE
Adding Verta to MLOps Platform Comparison spreadsheet

### ISSUE THREAD

**Issue by MCuny89** [mlops-platforms/mlops-platforms#7]
Hello,
I would like to add our column to the spreadsheet.

File: [GoogleSheet](https://docs.google.com/spreadsheets/d/1gjifpYW5Nw1qIxmkLA1hBjV92NrlE4k6AkJ9ZbwzA6k/edit?usp=sharing)

Changes: Added column 'B' providing information for [Verta](https://www.verta.ai/), no other changes has been made.

Thanks in advance!
Molly Cuny
Brand Designer at Verta

**Comment by ryandawsonuk** [comment]
This is now in the public sheet as column R. I only made small wording changes, mostly to reduce the number of words. Please have a look and let us know if there's anything you'd like changed.
